/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.rptis.landtax.province.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

@Template(FormPage.class)
@StyleSheet
public class NewManualLedgerPage extends javax.swing.JPanel {

    /**
     * Creates new form FAASSearchPage
     */
    public NewManualLedgerPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xComboBox5 = new com.rameses.rcp.control.XComboBox();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xComboBox4 = new com.rameses.rcp.control.XComboBox();
        xTextField6 = new com.rameses.rcp.control.XTextField();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xTextField7 = new com.rameses.rcp.control.XTextField();
        xTextField8 = new com.rameses.rcp.control.XTextField();
        xDecimalField3 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField4 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField2 = new com.rameses.rcp.control.XDecimalField();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xComboBox6 = new com.rameses.rcp.control.XComboBox();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setPadding(new java.awt.Insets(25, 10, 10, 10));
        xTitledBorder1.setTitle("New Ledger Information");
        xFormPanel1.setBorder(xTitledBorder1);
        xFormPanel1.setCaptionWidth(130);

        xComboBox5.setCaption("Municipality");
        xComboBox5.setExpression("#{item.name}");
        xComboBox5.setItems("municipalities");
        xComboBox5.setName("faas.lgu"); // NOI18N
        xComboBox5.setIndex(-1);
        xComboBox5.setPreferredSize(new java.awt.Dimension(0, 20));
        xComboBox5.setRequired(true);
        xFormPanel1.add(xComboBox5);

        xComboBox1.setCaption("Barangay");
        xComboBox1.setDepends(new String[] {"faas.lgu"});
        xComboBox1.setExpression("#{item.name}");
        xComboBox1.setItems("barangays");
        xComboBox1.setName("faas.rp.barangay"); // NOI18N
        xComboBox1.setDynamic(true);
        xComboBox1.setIndex(-1);
        xComboBox1.setPreferredSize(new java.awt.Dimension(0, 20));
        xComboBox1.setRequired(true);
        xFormPanel1.add(xComboBox1);

        xComboBox3.setCaption("Property Kind");
        xComboBox3.setItems("rputypes");
        xComboBox3.setName("faas.rpu.rputype"); // NOI18N
        xComboBox3.setAllowNull(false);
        xComboBox3.setPreferredSize(new java.awt.Dimension(0, 20));
        xComboBox3.setRequired(true);
        xFormPanel1.add(xComboBox3);

        xComboBox2.setCaption("Transaction");
        xComboBox2.setExpression("#{item.name}");
        xComboBox2.setItems("txntypes");
        xComboBox2.setName("faas.txntype"); // NOI18N
        xComboBox2.setPreferredSize(new java.awt.Dimension(0, 20));
        xComboBox2.setRequired(true);
        xFormPanel1.add(xComboBox2);

        xTextField1.setCaption("TD No.");
        xTextField1.setName("faas.tdno"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField1.setRequired(true);
        xFormPanel1.add(xTextField1);

        xTextField3.setCaption("Previous TD No.");
        xTextField3.setName("faas.prevtdno"); // NOI18N
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField3);

        xTextField2.setCaption("PIN");
        xTextField2.setName("faas.fullpin"); // NOI18N
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField2.setRequired(true);
        xFormPanel1.add(xTextField2);

        xComboBox4.setCaption("Classification");
        xComboBox4.setExpression("#{item.name}");
        xComboBox4.setItems("classifications");
        xComboBox4.setName("faas.rpu.classification"); // NOI18N
        xComboBox4.setAllowNull(false);
        xComboBox4.setPreferredSize(new java.awt.Dimension(0, 20));
        xComboBox4.setRequired(true);
        xFormPanel1.add(xComboBox4);

        xTextField6.setCaption("Cadastral Lot No.");
        xTextField6.setDepends(new String[] {"faas.rpu.rputype"});
        xTextField6.setName("faas.rp.cadastrallotno"); // NOI18N
        xTextField6.setVisibleWhen("#{faas.rpu.rputype == 'land'}");
        xTextField6.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField6.setRequired(true);
        xFormPanel1.add(xTextField6);

        xTextField5.setCaption("Block No.");
        xTextField5.setDepends(new String[] {"faas.rpu.rputype"});
        xTextField5.setName("faas.rp.blockno"); // NOI18N
        xTextField5.setVisibleWhen("#{faas.rpu.rputype == 'land'}");
        xTextField5.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField5);

        xTextField4.setCaption("Title No.");
        xTextField4.setDepends(new String[] {"faas.rputype"});
        xTextField4.setName("faas.rp.titleno"); // NOI18N
        xTextField4.setVisibleWhen("#{faas.rpu.rputype == 'land'}");
        xTextField4.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField4);

        xLookupField1.setCaption("Property Owner");
        xLookupField1.setExpression("#{item.name}");
        xLookupField1.setHandler("entity:lookup");
        xLookupField1.setName("faas.taxpayer"); // NOI18N
        xLookupField1.setCellPadding(new java.awt.Insets(10, 0, 0, 0));
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xLookupField1.setRequired(true);
        xFormPanel1.add(xLookupField1);

        xLabel1.setCaption("Address");
        xLabel1.setDepends(new String[] {"faas.taxpayer"});
        xLabel1.setExpression("#{faas.taxpayer.address.text}");
        xLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel1);

        xTextField7.setCaption("Declared Owner");
        xTextField7.setName("faas.owner.name"); // NOI18N
        xTextField7.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField7.setRequired(true);
        xFormPanel1.add(xTextField7);

        xTextField8.setCaption("Administrator");
        xTextField8.setName("faas.administrator.name"); // NOI18N
        xTextField8.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField8);

        xDecimalField3.setCaption("Area (ha)");
        xDecimalField3.setDepends(new String[] {"faas.rpu.classification"});
        xDecimalField3.setName("faas.rpu.totalareaha"); // NOI18N
        xDecimalField3.setPattern("#,##0.0000");
        xDecimalField3.setScale(4);
        xDecimalField3.setVisibleWhen("#{faas.rpu.classification.name == 'AGRICULTURAL'}");
        xDecimalField3.setCellPadding(new java.awt.Insets(10, 0, 0, 0));
        xDecimalField3.setPreferredSize(new java.awt.Dimension(140, 20));
        xDecimalField3.setRequired(true);
        xFormPanel1.add(xDecimalField3);

        xDecimalField4.setCaption("Area (sqm)");
        xDecimalField4.setDepends(new String[] {"faas.rpu.classification"});
        xDecimalField4.setName("faas.rpu.totalareasqm"); // NOI18N
        xDecimalField4.setVisibleWhen("#{faas.rpu.classification.name != 'AGRICULTURAL'}");
        xDecimalField4.setCellPadding(new java.awt.Insets(10, 0, 0, 0));
        xDecimalField4.setPreferredSize(new java.awt.Dimension(140, 20));
        xDecimalField4.setRequired(true);
        xFormPanel1.add(xDecimalField4);

        xDecimalField1.setCaption("Market Value");
        xDecimalField1.setName("faas.rpu.totalmv"); // NOI18N
        xDecimalField1.setPreferredSize(new java.awt.Dimension(140, 20));
        xDecimalField1.setRequired(true);
        xFormPanel1.add(xDecimalField1);

        xDecimalField2.setCaption("Assessed Value");
        xDecimalField2.setName("faas.rpu.totalav"); // NOI18N
        xDecimalField2.setPreferredSize(new java.awt.Dimension(140, 20));
        xDecimalField2.setRequired(true);
        xFormPanel1.add(xDecimalField2);

        xIntegerField1.setCaption("Effectivity Year");
        xIntegerField1.setName("faas.effectivityyear"); // NOI18N
        xIntegerField1.setPreferredSize(new java.awt.Dimension(90, 20));
        xIntegerField1.setRequired(true);
        xFormPanel1.add(xIntegerField1);

        xComboBox6.setCaption("Effectivity Qtr");
        xComboBox6.setItems("quarters");
        xComboBox6.setName("faas.effectivityqtr"); // NOI18N
        xComboBox6.setAllowNull(false);
        xComboBox6.setPreferredSize(new java.awt.Dimension(90, 20));
        xComboBox6.setRequired(true);
        xFormPanel1.add(xComboBox6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XComboBox xComboBox4;
    private com.rameses.rcp.control.XComboBox xComboBox5;
    private com.rameses.rcp.control.XComboBox xComboBox6;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XDecimalField xDecimalField2;
    private com.rameses.rcp.control.XDecimalField xDecimalField3;
    private com.rameses.rcp.control.XDecimalField xDecimalField4;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField6;
    private com.rameses.rcp.control.XTextField xTextField7;
    private com.rameses.rcp.control.XTextField xTextField8;
    // End of variables declaration//GEN-END:variables
}
